# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Data_size', models.IntegerField()),
                ('Data_win', models.IntegerField()),
                ('Data_minc', models.IntegerField()),
                ('Data_xls', models.FileField(blank=True, default=None, null=True, upload_to='')),
            ],
            options={
                'db_table': 'Data',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tags_text', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ('Tags_text',),
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=300)),
                ('win', models.IntegerField(default=5)),
                ('minc', models.IntegerField(default=30)),
            ],
            options={
                'db_table': 'Temp',
            },
        ),
        migrations.AddField(
            model_name='data',
            name='Data_tags',
            field=models.ManyToManyField(to='WV.Tags'),
        ),
    ]
