# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-19 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_size', models.IntegerField(default=0)),
                ('Data_win', models.IntegerField(default=0)),
                ('Data_minc', models.IntegerField(default=0)),
                ('Data_xls', models.FileField(blank=True, default=None, null=True, upload_to='C:/Users/Artur/PycharmProjects/Word2Vec/WV/media')),
            ],
            options={
                'db_table': 'Data',
            },
        ),
    ]
