# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WV', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='Data_title',
        ),
    ]
