# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WV', '0003_data_data_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('win', models.IntegerField()),
                ('minc', models.IntegerField()),
                ('xls', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='')),
            ],
            options={
                'db_table': 'Options',
            },
        ),
        migrations.RemoveField(
            model_name='data',
            name='Data_minc',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Data_size',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Data_tags',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Data_win',
        ),
        migrations.RemoveField(
            model_name='data',
            name='Data_xls',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AddField(
            model_name='options',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WV.Data'),
        ),
    ]
