# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WV', '0004_auto_20170724_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='xls',
        ),
        migrations.AddField(
            model_name='data',
            name='Data_xls',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
