# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WV', '0006_auto_20170724_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='html',
        ),
        migrations.AddField(
            model_name='options',
            name='components',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
