# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WV', '0007_auto_20170724_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='components',
            new_name='div',
        ),
        migrations.AddField(
            model_name='options',
            name='script',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
