# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WV', '0008_auto_20170724_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tags_text', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ('Tags_text',),
            },
        ),
        migrations.AddField(
            model_name='data',
            name='Data_tags',
            field=models.ManyToManyField(to='WV.Tags'),
        ),
    ]
