# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WV', '0009_auto_20170725_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={},
        ),
        migrations.RemoveField(
            model_name='data',
            name='Data_tags',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='Tags_text',
        ),
        migrations.AddField(
            model_name='tags',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WV.Data'),
        ),
        migrations.AddField(
            model_name='tags',
            name='tg',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
