# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-07 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WV', '0010_auto_20170725_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WV.Data'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TAGS', to='WV.Data'),
        ),
    ]
