# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-08 08:18
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WV', '0011_auto_20170807_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='cbow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='options',
            name='skipgr',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='options',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(location='/opt/static/'), upload_to=''),
        ),
    ]
