# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-09 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WV', '0012_auto_20170808_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='num_clusters',
            field=models.IntegerField(default=0),
        ),
    ]
