# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-15 10:48
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WV', '0013_options_num_clusters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_clusters', models.IntegerField(default=20)),
                ('img', models.ImageField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(location='/opt/static/'), upload_to='')),
                ('script', models.TextField(blank=True, default=None, null=True)),
                ('div', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'Images',
            },
        ),
        migrations.RemoveField(
            model_name='options',
            name='div',
        ),
        migrations.RemoveField(
            model_name='options',
            name='img',
        ),
        migrations.RemoveField(
            model_name='options',
            name='num_clusters',
        ),
        migrations.RemoveField(
            model_name='options',
            name='script',
        ),
        migrations.AddField(
            model_name='options',
            name='alg',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='imageoptions',
            name='opt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='WV.Options'),
        ),
    ]
