# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-16 13:42
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WV', '0014_auto_20170815_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='preview',
            field=models.ImageField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(location='/opt/static/'), upload_to=''),
        ),
    ]
