# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WV', '0015_options_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Data_model',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
