# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WV', '0016_data_data_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageoptions',
            name='num_neighbors',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
